language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - python --version
  - pip install -U pip  # update pip, because why not
  - pip install -U pytest  # dev only dependency
  - pip install -U flask
  - pip install -U gevent
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
