site_name: Pyourls3 1.0.0

repo_url: https://www.github.com/codemicro/pyourls3
repo_name: GitHub

copyright: Copyright © Thomas Pain <script>document.write(new Date().getFullYear());</script>
site_author: Thomas Pain
site_description: The docs for Pyourls3 - A Python 3 API wrapper for YOURLS

theme:
  name: bootstrap386

use_directory_urls: false
nav:
    - Home: index.md
    - Guides:
        - Getting started: start.md
    - Documentation:
        - API reference: api.md
        - Contributing: contributing.md
        - Testing: test.md